---

# create giscube database and user, assign privileges
# CREATE DATABASE giscube WITH template=postgis_template;
- postgresql_db: name=giscube
                 encoding='UTF-8'
                 template='postgis_template'
  become: yes
  become_user: postgres

# create giscube user, assign privileges
# CREATE USER giscube WITH PASSWORD 'giscube'
- include: create_user_and_schema.yml
  vars:
      user_name: "{{ postgresql_giscube_username }}"
      user_password: "{{ postgresql_giscube_password }}"

# GRANT ALL PRIVILEGES ON DATABASE giscube TO giscube
- postgresql_privs: >
    db=giscube
    privs=ALL
    type=database
    role={{ postgresql_giscube_username }}
  become: yes
  become_user: postgres

# create test user, assign privileges
# CREATE USER test WITH PASSWORD 'test'
- include: create_user_and_schema.yml
  vars:
      user_name: "{{ postgresql_test_username }}"
      user_password: "{{ postgresql_test_password }}"
